-- 1. Bảng Kho Hàng
CREATE TABLE crm_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code TEXT, item_name TEXT, specs TEXT, qty NUMERIC,
    buying_price_rmb NUMERIC, total_buying_price_rmb TEXT,
    exchange_rate NUMERIC, buying_price_vnd NUMERIC,
    total_buying_price_vnd TEXT, leadtime TEXT, supplier_name TEXT,
    image_path TEXT, type TEXT, nuoc TEXT
);

-- 2. Bảng Lịch sử dùng chung (Quan trọng cho Tab 3)
CREATE TABLE crm_shared_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id TEXT, date TEXT, quote_no TEXT, customer TEXT,
    item_code TEXT, item_name TEXT, specs TEXT, qty NUMERIC,
    unit_price NUMERIC, total_price_vnd NUMERIC, profit_vnd NUMERIC,
    gap NUMERIC, end_user_val NUMERIC, buyer_val NUMERIC,
    mgmt_fee NUMERIC, transportation NUMERIC, import_tax_val NUMERIC, vat_val NUMERIC
);

-- 3. Bảng PO và Tracking
CREATE TABLE db_supplier_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT, supplier TEXT, order_date TEXT,
    item_code TEXT, qty NUMERIC, price_vnd NUMERIC, total_vnd NUMERIC
);

CREATE TABLE db_customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT, customer TEXT, order_date TEXT,
    item_code TEXT, qty NUMERIC, total_price NUMERIC
);

CREATE TABLE crm_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_no TEXT, partner TEXT, status TEXT, 
    proof_image TEXT, order_type TEXT, last_update TEXT
);
